### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by heyalbert** [roots/roots-sass#30]
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.29
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE
npm ERR! roots@7.0.1 postinstall: `node node_modules/bower/bin/bower install && grunt dev`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the roots@7.0.1 postinstall script 'node node_modules/bower/bin/bower install && grunt dev'.
npm ERR! This is most likely a problem with the roots package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/bower/bin/bower install && grunt dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls roots
npm ERR! There is likely additional logging output above.

**Comment by heyalbert** [comment]
tried to fixed with help in this issue: https://github.com/roots/roots/issues/1078

run in the next error:
$ grunt dev
Running "jshint:all" (jshint) task
>> 2 files lint free.

Running "sass:dev" (sass) task
ERROR: Cannot load compass.
Warning: Exited with error code 1 Use --force to continue.

Aborted due to warnings.


Execution Time (2015-01-29 11:01:26 UTC)
jshint:all   102ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 20%
sass:dev     403ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 79%
Total 509ms

**Comment by swalkinshaw** [comment]
This repository is being deprecated and this is a Roots issue anyway that will be gone in the next version (Sage 8.0.0).

**Comment by nmaxcom** [comment]
I'm experiencing (I think) the same error in OSX:

**[...]**
Running "jshint:all" (jshint) task
>> 2 files lint free.

Running "less:dev" (less) task
>> SyntaxError: Cannot find module 'source-map' in assets/less/main.less on line null, column 0:
>> 1 @import "_bootstrap";
Warning: Error compiling assets/less/main.less Use --force to continue.

Aborted due to warnings.


Execution Time (2015-02-01 01:36:20 UTC)
jshint:all  149ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 11%
less:dev     1.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 88%
Total 1.3s


npm ERR! roots@7.0.3 postinstall: `node node_modules/bower/bin/bower install && grunt dev`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the roots@7.0.3 postinstall script.
npm ERR! This is most likely a problem with the roots package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/bower/bin/bower install && grunt dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls roots
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /folder/to/wp/theme
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /folder/to/wp/theme/npm-debug.log
npm ERR! not ok code 0


Any temporary fix? I'm pretty new with the whole npm/grunt/bower thing.
